version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - django_gallery_db:/var/lib/postgresql/data

volumes:
  django_gallery_db: